/**:
  ros__parameters:
    general:
      grab_resolution: HD720
      grab_frame_rate: 15
      pub_resolution: NATIVE
      pub_frame_rate: 15.0

    video:
      publish_rgb: true
      publish_left_right: true
      publish_raw: false
      publish_gray: false
      publish_stereo: true

    sensors:
      publish_imu: true
      publish_imu_raw: true
      sensors_pub_rate: 100.0
      sensors_image_sync: false
      publish_cam_imu_transf: true

    depth:
      depth_mode: NONE
      publish_depth_map: false
      publish_point_cloud: false
      publish_disparity: false

    pos_tracking:
      pos_tracking_enabled: false
      publish_tf: false
      publish_map_tf: false
